COMPILER = C:\MinGW\bin\gcc.exe
CFLAGS+= -pedantic -Wall -Werror -std=c99 -O0

program: main.c queue.o
	${COMPILER} ${CFLAGS} main.c queue.o -o program

queue.o: queue.c queue.h
	${COMPILER} ${CFLAGS} -c queue.c -o queue.o
	
zip:
	zip hw10-us.zip queue.h queue.c
	
clean:
	del -f *.o
	del -f program
	del -f hw10-us.zip

